/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventario_tienda_compensar;

import java.awt.*;
import java.net.URL;
import java.util.ArrayList;

/**
 *
 * @author manyd
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    public Image getIconImage() {
        Image value = null;
        URL imageUrl = ClassLoader.getSystemResource("images/logo-ucompensar-2022.jpg");
        if (imageUrl != null) {
            value = Toolkit.getDefaultToolkit().getImage(imageUrl);
        } else {
            // Manejar el caso en que la imagen no se pueda cargar
            // Por ejemplo, cargar una imagen predeterminada
            // value = Toolkit.getDefaultToolkit().getImage("ruta/a/imagen/predeterminada.jpg");
        }
        return value;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        saveProjectBtn = new javax.swing.JMenuItem();
        createProjectBtn = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        registerProductsBtn = new javax.swing.JMenuItem();
        registerEmployeesBtn = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        graphicProductsBtn = new javax.swing.JMenuItem();
        graphicEmployeesBtn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        aboutUsBtn = new javax.swing.JMenuItem();
        ucompensarBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        saveProjectBtn.setText("Guardar Proyecto");
        saveProjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProjectBtnActionPerformed(evt);
            }
        });
        jMenu1.add(saveProjectBtn);

        createProjectBtn.setText("Crear Proyecto");
        createProjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProjectBtnActionPerformed(evt);
            }
        });
        jMenu1.add(createProjectBtn);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Registro");

        registerProductsBtn.setText("Registro Productos");
        registerProductsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerProductsBtnActionPerformed(evt);
            }
        });
        jMenu3.add(registerProductsBtn);

        registerEmployeesBtn.setText("Registro Empleados");
        registerEmployeesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerEmployeesBtnActionPerformed(evt);
            }
        });
        jMenu3.add(registerEmployeesBtn);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Graficar");

        graphicProductsBtn.setText("Graficar Productos");
        graphicProductsBtn.setEnabled(false);
        graphicProductsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphicProductsBtnActionPerformed(evt);
            }
        });
        jMenu5.add(graphicProductsBtn);

        graphicEmployeesBtn.setText("Graficar Empleados");
        graphicEmployeesBtn.setEnabled(false);
        graphicEmployeesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphicEmployeesBtnActionPerformed(evt);
            }
        });
        jMenu5.add(graphicEmployeesBtn);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Ayuda");

        jMenu4.setText("Sobre Nosotros");

        aboutUsBtn.setText("Sobre Nosotros");
        aboutUsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsBtnActionPerformed(evt);
            }
        });
        jMenu4.add(aboutUsBtn);

        ucompensarBtn.setText("UCompensar");
        ucompensarBtn.setToolTipText("");
        ucompensarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ucompensarBtnActionPerformed(evt);
            }
        });
        jMenu4.add(ucompensarBtn);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    ProductsInterface productsInterface = new ProductsInterface();
    /**
     * Maneja el evento de clic en el botón de registrar productos.
     * Agrega la interfaz de productos al panel de escritorio, la muestra y habilita el botón gráfico de productos.
     * @param evt El evento de acción que desencadenó este método.
     */
    private void registerProductsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerProductsBtnActionPerformed
        // Se agrega la interfaz de productos al panel de escritorio.
        desktopPane.add(productsInterface);
        // Se muestra la interfaz de productos.
        productsInterface.show();
        // Se habilita el botón gráfico de productos.
        graphicProductsBtn.setEnabled(true);

    }//GEN-LAST:event_registerProductsBtnActionPerformed

    EmployeesInterface employeesInterface = new EmployeesInterface();
    private void registerEmployeesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerEmployeesBtnActionPerformed
        desktopPane.add(employeesInterface);
        employeesInterface.show();
        graphicEmployeesBtn.setEnabled(true);
    }//GEN-LAST:event_registerEmployeesBtnActionPerformed

    private void saveProjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProjectBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveProjectBtnActionPerformed

    private void createProjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProjectBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createProjectBtnActionPerformed

    private void aboutUsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutUsBtnActionPerformed

    private void ucompensarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ucompensarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ucompensarBtnActionPerformed

    private void graphicProductsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphicProductsBtnActionPerformed
        ArrayList<Product> productTemp = productsInterface.products;
        for(Product p : productTemp)
            System.out.println(p.toString());
        int unitsSoldAseo = 0;
        int unitsSoldViveres = 0;
        int unitsSoldMascotas = 0;
        int unitsSoldPapeleria = 0;
        int unitsSoldOtros = 0;
        for(Product product : productTemp){
            switch(product.getType()){
                case "Aseo":
                    unitsSoldAseo += product.getTotalUnits();
                    break;
                case "Papelería":
                    unitsSoldPapeleria += product.getTotalUnits();
                    break;
                case "Víveres":
                    unitsSoldViveres += product.getTotalUnits();
                    break;
                case "Productos para Mascotas":
                    unitsSoldMascotas += product.getTotalUnits();
                    break;
                case "Otros":
                    unitsSoldOtros += product.getTotalUnits();
                    break;
            }
        }


        ProductGraphicFrame productGraphicFrame = new ProductGraphicFrame(unitsSoldAseo, unitsSoldPapeleria, unitsSoldViveres, unitsSoldMascotas, unitsSoldOtros);
        desktopPane.add(productGraphicFrame);
        productGraphicFrame.show();
        productGraphicFrame.repaint();
    }//GEN-LAST:event_graphicProductsBtnActionPerformed

    private void graphicEmployeesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphicEmployeesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_graphicEmployeesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutUsBtn;
    private javax.swing.JMenuItem createProjectBtn;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem graphicEmployeesBtn;
    private javax.swing.JMenuItem graphicProductsBtn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem registerEmployeesBtn;
    private javax.swing.JMenuItem registerProductsBtn;
    private javax.swing.JMenuItem saveProjectBtn;
    private javax.swing.JMenuItem ucompensarBtn;
    // End of variables declaration//GEN-END:variables
}
