/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.inventario_tienda_compensar;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author manyd
 */
public class ProductGraphicFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProductGraphicFrame
     */
    int unitsSoldAseo;
    int unitsSoldPapeleria;
    int unitsSoldViveres;
    int unitsSoldMascotas;
    int unitsSoldOtros;

    public ProductGraphicFrame() {
        initComponents();
    }

    public ProductGraphicFrame(int unitsSoldAseo, int unitsSoldPapeleria, int unitsSoldViveres, int unitsSoldMascotas, int unitsSoldOtros) {
        this.unitsSoldAseo = unitsSoldAseo;
        this.unitsSoldPapeleria = unitsSoldPapeleria;
        this.unitsSoldViveres = unitsSoldViveres;
        this.unitsSoldMascotas = unitsSoldMascotas;
        this.unitsSoldOtros = unitsSoldOtros;
        initComponents();
    }

    public void paint(Graphics g){
        super.paint(g);
        int totalSold = unitsSoldAseo + unitsSoldPapeleria + unitsSoldViveres + unitsSoldMascotas + unitsSoldOtros;
        int aseoGrades = unitsSoldAseo * 360 / totalSold;
        int papeleriaGrades = unitsSoldPapeleria * 360 / totalSold;
        int viveresGrades = unitsSoldViveres * 360 / totalSold;
        int mascotasGrades = unitsSoldMascotas * 360 / totalSold;
        int otrosGrades = unitsSoldOtros * 360 / totalSold;

        System.out.println(aseoGrades);
        System.out.println(totalSold);
        System.out.println(unitsSoldAseo);
        System.out.println(unitsSoldPapeleria);
        System.out.println(unitsSoldViveres);
        System.out.println(unitsSoldMascotas);
        System.out.println(unitsSoldOtros);
        g.setColor(Color.ORANGE);
        g.fillArc(25, 80, 200, 200,0,aseoGrades);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
